dist: xenial 
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install codecov
  - pip install pycodestyle
script:
  - pycodestyle .
  - coverage run --source=src setup.py test
after_success:
  - codecov
