site_name: Introduction to Algorithms
theme: readthedocs
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML', 'mathjaxconfig.js']
pages:
- 'Introduction': 'index.md'
- '2 Getting Started':
    - '2.1 Insertion sort': '2-Getting-Started/2.1-Insertion-sort.md'
    - '2.2 Analyzing algorithms': '2-Getting-Started/2.2-Analyzing-algorithms.md'
    - '2.3 Designing algorithms': '2-Getting-Started/2.3-Designing-algorithms.md'
    - 'Problems': '2-Getting-Started/Problems.md'
- '3 Growth of Functions':
    - '3.1 Asymptotic notation': '3-Growth-of-Functions/3.1-Asymptotic-notation.md'
    - '3.2 Standard notations and common functions': '3-Growth-of-Functions/3.2-Standard-notations-and-common-functions.md'
    - 'Problems': '3-Growth-of-Functions/Problems.md'
- '4 Divide and Conquer':
    - '4.1 The maximum-subarray problem': '4-Divide-and-Conquer/4.1-The-maximum-subarray-problem.md'
    - '4.2 Strassen''s algorithm for matrix multiplication': '4-Divide-and-Conquer/4.2-Strassen''s-algorithm-for-matrix-multiplication.md'
    - '4.3 The substitution method for solving recurrences': '4-Divide-and-Conquer/4.3-The-substitution-method-for-solving-recurrences.md'
    - '4.4 The recursion-tree method for solving recurrences': '4-Divide-and-Conquer/4.4-The-recursion-tree-method-for-solving-recurrences.md'
    - '4.5 The master method for solving recurrences': '4-Divide-and-Conquer/4.5-The-master-method-for-solving-recurrences.md'
    - '4.6 Proof of the master theorem': '4-Divide-and-Conquer/4.6-Proof-of-the-master-theorem.md'
    - 'Problems': '4-Divide-and-Conquer/Problems.md'
- '5 Probabilistic Analysis and Randomized Algorithms':
    - '5.1 The hiring problem': '5-Probabilistic-Analysis-and-Randomized-Algorithms/5.1-The-hiring-problem.md'
    - '5.2 Indicator random variables': '5-Probabilistic-Analysis-and-Randomized-Algorithms/5.2-Indicator-random-variables.md'
    - '5.3 Randomized algorithms': '5-Probabilistic-Analysis-and-Randomized-Algorithms/5.3-Randomized-algorithms.md'
    - '5.4 Probabilistic analysis and further uses of indicator random variables': '5-Probabilistic-Analysis-and-Randomized-Algorithms/5.4-Probabilistic-analysis-and-further-uses-of-indicator-random-variables.md'
    - 'Problems': '5-Probabilistic-Analysis-and-Randomized-Algorithms/Problems.md'
- '6 Heapsort':
    - '6.1 Heaps': '6-Heapsort/6.1-Heaps.md'
    - '6.2 Maintaining the heap property': '6-Heapsort/6.2-Maintaining-the-heap-property.md'
    - '6.3 Building a heap': '6-Heapsort/6.3-Building-a-heap.md'
    - '6.4 The heapsort algorithm': '6-Heapsort/6.4-The-heapsort-algorithm.md'
    - '6.5 Priority queues': '6-Heapsort/6.5-Priority-queues.md'
    - 'Problems': '6-Heapsort/Problems.md'
- '7 Quicksort':
    - '7.1 Description of quicksort': '7-Quicksort/7.1-Description-of-quicksort.md'
    - '7.2 Performance of quicksort': '7-Quicksort/7.2-Performance-of-quicksort.md'
    - '7.3 A randomized version of quicksort': '7-Quicksort/7.3-A-randomized-version-of-quicksort.md'
    - '7.4 Analysis of quicksort': '7-Quicksort/7.4-Analysis-of-quicksort.md'
    - 'Problems': '7-Quicksort/Problems.md'
- '8 Sorting in Linear Time':
    - '8.1 Lower bounds for sorting': '8-Sorting-in-Linear-Time/8.1-Lower-bounds-for-sorting.md'
    - '8.2 Counting sort': '8-Sorting-in-Linear-Time/8.2-Counting-sort.md'
    - '8.3 Radix sort': '8-Sorting-in-Linear-Time/8.3-Radix-sort.md'
    - '8.4 Bucket sort': '8-Sorting-in-Linear-Time/8.4-Bucket-sort.md'
    - 'Problems': '8-Sorting-in-Linear-Time/Problems.md'
- '9 Medians and Order Statistics':
    - '9.1 Minimum and maximum': '9-Medians-and-Order-Statistics/9.1-Minimum-and-maximum.md'
    - '9.2 Selection in expected linear time': '9-Medians-and-Order-Statistics/9.2-Selection-in-expected-linear-time.md'
    - '9.3 Selection in worst-case linear time': '9-Medians-and-Order-Statistics/9.3-Selection-in-worst-case-linear-time.md'
    - 'Problems': '9-Medians-and-Order-Statistics/Problems.md'
- '10 Elementary Data Structures':
    - '10.1 Stacks and queues': '10-Elementary-Data-Structures/10.1-Stacks-and-queues.md'
    - '10.2 Linked lists': '10-Elementary-Data-Structures/10.2-Linked-lists.md'